baseurl = "http://www.roylarsen.xyz/"
title = "roybot"
languageCode = "en-us"

theme = "hugo-bootstrap-premium"

paginate = 5
paginatePath = "page"

[author]
  name = "Roy Larsen"
  email = "info@roylarsen.xyz"

[params.theme]
  name = "cosmo"
[params]
  home = "Home"
  showiRightSidebar = true
  github = "roylarsen"

[Languages]
  [Languages.en]
    title = "roylarsen.xyz"
    [[Languages.en.menu.main]]
      name = "home."
      weight = 1
      url = "http://www.roylarsen.xyz"
    [[Languages.en.menu.main]]
      name = "about."
      weight = 1
      url = "http://www.roylarsen.xyz/about"
    [[Languages.en.menu.main]]
      name = "blag."
      weight = 1
      url = "http://www.roylarsen.xyz/posts/"
